image: python:3.8

stages:
  - build
  - test
  - deploy

build_model:
  stage: build
  script:
    - pip install -r requirements.txt

test_model:
  stage: test
  script:
    - python src/train.py

deploy_model:
  stage: deploy
  script:
    - echo "Deploying model..."
    # Add deployment commands here (e.g., copy files to a server or cloud service)